# Jinja variables help maintain the recipe as you'll update the version only here.
{% set version = "4.3" %}
{% set sha256 = "e05fdde47c5f7ca45cb697e973894ff4f5d79e13b750ed57d7b66d8defc78e19" %}

package:
  name: make
  version: {{ version }}

source:
  fn: make-{{ version }}.tar.bz2
  url: https://ftp.gnu.org/gnu/make/make-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 1
{% endif %}
  detect_binary_files_with_prefix: false
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}

requirements:
  build:
{% if bootstrapping != 'yes' %}
    - libtool  # [unix]
    - bash     # [unix]
{% endif %}
    - {{ compiler("c") }}        # [unix]
    - {{ compiler("m2w64_c") }}  # [win]
    - make  # [build_platform != target_platform]
  host:
  run:

test:
  commands:
    - $PREFIX/bin/make --help  # [unix]
    - '"%LIBRARY_BIN%\gnumake.exe" --help'  # [win]
    - '"%LIBRARY_BIN%\make.exe" --help'  # [win]

about:
  home: https://www.gnu.org/software/make/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: >-
    GNU Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files.
  doc_url: https://www.gnu.org/software/make/manual/

extra:
  recipe-maintainers:
    - asmeurer
    - scopatz
