appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZI6zE8gSemuVhNUpGAbXCCmo9jK1LqVFg1wobBCTa4XDNNAn2JSLAMyaor05paisB8RSTmCzKTLnxNLa5Wii76KyCrXGKvcbZKiP89XddiWGM5B2j1tkbSJo4TrlsPpHIopkChfaiXnuRzmaqECp2PZ/0ZlAQtaBRHAj6aMPHRjlIlPyg6wixxOO40SYHy9QDIh0AsAFJ7s+o40dHYgw19PBy4/deQCLlr6lal0LDzSP32VSuJAhhHv3lbn/kT9Biv58aj5Nm36ESeS5J5QiNE2I8LtxPH1TCkjU1BJOywXf6P+f+xHf+2CUHtliVEyWyBgATlOspjX4cbMX0o96uaIO2vdP1Fb4QakuvVLtmqPOEIv663hvMZUxoy08DV1tcvKREuirNdPOYTRjNhrZu4k/e9bdT0hXRJBaFUkuqLAnVsKOgrjGl6DvLBtzXJOd6EVTSwDFB9q5F/IBSpU4plrDU4BCpoasqAaQNU4ABLQiQUY4hqv5dR++4Xrwgg3NssJlMGLAnZvc0R6m56HR6XAtWJGEGQitk8/Xi/BbL9UVWsjJBcTeS/Y5oolbowqY91z+nQDRsfE61fVqYeJ1zkg7YUELPxnTUrV+pgdq/Jti0xVdhIzgm7tkjqyRCjjl7gQMpT6qBBbmKG8x6cMiTSUMR4hS9Snw1b7LAC+rNSY=}
